research_task:
  description: >
    Conduct a search for job opportunities based on the provided query.
    You can adapt the query to be more specific based on the resume sended as source.
    This is my first english speaking work, so I want to find opportunities that are compatible with my experience and that are not looking for a legal worker in the US or Canada.
    Use this query: {query} as a base for the search.
    You can also prioritize opportunities that specify they are looking for a remote worker or are LATAM
    Use the Google search tool to find job posts that are a good fit with the given resume.
    Focus on finding the most relevant job posts that are compatible with the resume.
    You can also discard opportunities that are not compatible with the candidate's experience or that were published a long time ago.
    Return a list of job posts that have the best match with the given resume source with a salary range between 0 to $100k or undefined.
    You can search multiple times and change the query to get better results. Max of 5 searches.
    The final output must have at least 30 job posts
  expected_output: >
    A list with job posts that have the best match with the given resume source.
  agent: job_opportunities_scrapper

reporting_task:
  description: >
    Review the context you got and expand each opportunity retrieved with informations about the company's reputation.
    Use sites like Glassdoor, Indeed, and LinkedIn to gather data on the company's reputation
    for each opportunity in the list retrieved by the job_opportunities_scrapper. Exclude opportunities that looks like scam.
    Return a detailed report with the following information for the best 10 opportunities:
    - Company name
    - Company reputation (from 1 to 5)
    - Average salary for the position (if available)
    - Opportunity link
    - Job title
    Ensure that the report is comprehensive and provides a clear overview of the job opportunities.

  expected_output: >
    A report containing a ranked list of the best job opportunities with detailed information about each company. and the job opportunities Links provided by the job_opportunities_scrapper.
  agent: business_analyst
